export const FEE_M_INFO = "This DApp is powered by Sonic FeeM – 90% of transaction fees go to support the developer.";

export const FEE_M_DETAILS = {
  enabled: true,
  network: "Sonic Blaze Testnet",
  chainId: 57054,
  rewardPercentage: 90,
  description: "FeeM automatically rewards DApp developers with 90% of transaction fees generated by their smart contracts on the Sonic blockchain."
};
